apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-store
  labels:
    app: next-store
spec:
  replicas: 10
  revisionHistoryLimit: 3
  template:
    spec:
      containers:
        - name: next-store
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 335m
              memory: 532Mi
