apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-store
  labels:
    app: next-store
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    spec:
      containers:
        - name: next-store
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
