apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: next-store-virtualservice
  namespace: default
spec:
  gateways:
  - admin-gateway
  hosts:
  - "*.new.meepshop.com"
  http:
  - route:
    - destination:
        host: next-store
        port:
          number: 14401
