export const COLORS = {
  black: '#000000',
  white: '#ffffff',
  red: '#ff0000',
  orange: '#ffa500',
  yellow: '#ffff00',
  green: '#008000',
  blue: '#0000ff',
  purple: '#800080',
};

export const FONTFAMILY = [
  'Arial',
  'Arial Black',
  'Comic Sans MS',
  'Courier',
  'Courier New',
  '標楷體',
  'Helvetica',
  'Impace',
  'Lucida Grande',
  'Lucida Sans',
  '微軟正黑體',
  'Monospace',
  '新細明體',
  'Sans Serif',
  'Serif',
  'Tahoma',
  'Times',
  'Times New Roman',
  'Verdana',
];
