version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm run install:all
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check code style
          command: |
            make babel-prod
            npm run lint -- .

      # TODO
      #- run:
      #    name: Test pacakges
      #    command: npm run test
      #- store_artifacts:
      #    path: coverage

  deploy:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm run install:all

      - run:
          name: Pre publish
          command: npm run prod
      - store_artifacts:
          path: packages/meep-ui/lib
      - store_artifacts:
          path: packages/store/src

      - run:
          name: Publish npm
          command: |
            test $(.circleci/bin/checkNeedPublish.js ./packages/meep-ui) = true && \
              npm run lerna -- publish \
              --skip-git \
              --force-publish=@meepshop/meep-ui \
              --repo-version ${CIRCLE_TAG} \
              --yes || \
              echo "not publish @meepshop/meep-ui@${CIRCLE_TAG}"

      - setup_remote_docker
      - run:
          name: Deploy docker
          command: |
            npm run lerna -- exec \
              "${CIRCLE_WORKING_DIRECTORY}/.circleci/bin/build_docker.sh ${CIRCLE_TAG}" \
              --parallel \
              --stream \
              --ignore @meepshop/meep-ui
            npm run lerna -- exec \
              "${CIRCLE_WORKING_DIRECTORY}/.circleci/bin/deploy_k8s.sh ${CIRCLE_TAG}" \
              --parallel \
              --stream \
              --ignore @meepshop/meep-ui

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
