version: 2
defaults: &defaults
  docker:
    - image: circleci/node:10.15.3-browsers
  working_directory: ~/repo

check-patches: &check-patches
  name: Check patches
  command: |
    for patch in $(ls ./patches); do
      cat ./patches/$patch >> patches.lock
    done

restore-cache: &restore-cache
  keys:
    - dependencies-{{ checksum "yarn.lock" }}-{{ checksum "patches.lock" }}

save-cache: &save-cache
  key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "patches.lock" }}
  paths:
    - node_modules

deploy-docker: &deploy-docker
  name: Deploy docker
  command: |
    yarn tsc:basic
    yarn prod
    yarn lerna run prod \
      --parallel \
      --stream \
      --scope @meepshop/store \
      --scope @admin/server
    yarn lerna exec \
      "${CIRCLE_WORKING_DIRECTORY}/.circleci/bin/build_docker.sh" \
      --parallel \
      --stream \
      --scope @admin/server \
      --scope @meepshop/store
    yarn lerna exec \
      "${CIRCLE_WORKING_DIRECTORY}/.circleci/bin/deploy_k8s.sh" \
      --parallel \
      --stream \
      --scope @admin/server \
      --scope @meepshop/store

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: *check-patches

      - restore_cache: *restore-cache
      - run:
          name: Install packages
          command: yarn install:all
      - save_cache: *save-cache

  lint-and-test:
    <<: *defaults
    steps:
      - checkout
      - run: *check-patches
      - restore_cache: *restore-cache
      - run: yarn lerna bootstrap

      - run:
          name: Check locale files
          command: |
            yarn lerna exec "babel src -d lib --config-file ../../babel.config.js --verbose -x .ts" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser check-keys @meepshop/store" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser check-keys @admin/server" \
              --stream \
              --scope @meepshop/locale-parser

      - run:
          name: Check code style
          command: |
            #TODO: remove after removing @meesphop/meep-ui
            yarn prod
            yarn tsc
            yarn lint .

      - run:
          name: Unit testing
          command: yarn test
      - store_artifacts:
          path: coverage

  deploy-test-branch:
    <<: *defaults
    steps:
      - checkout
      - run: *check-patches
      - restore_cache: *restore-cache
      - run: yarn lerna bootstrap
      - setup_remote_docker
      - run: *deploy-docker

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: *check-patches
      - restore_cache: *restore-cache
      - run: yarn lerna bootstrap
      - setup_remote_docker
      - run: *deploy-docker
      - run:
          name: Send locale notifier
          command: |
            yarn lerna exec "babel src -d lib --config-file ../../babel.config.js --verbose -x .ts" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser find-null @meepshop/store --send-glip" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser find-null @admin/server --send-glip" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser generate-csv @meepshop/store" \
              --stream \
              --scope @meepshop/locale-parser
            yarn lerna exec "yarn locale-parser generate-csv @admin/server" \
              --stream \
              --scope @meepshop/locale-parser
      - store_artifacts:
          path: locales

  deploy-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install:all
      - setup_remote_docker
      - run: *deploy-docker

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/

      - lint-and-test:
          context: org-global
          requires:
            - install
          filters:
            branches:
              ignore: /test-.*/
            tags:
              ignore: /.*/

      - deploy-test-branch:
          context: org-global
          requires:
            - install
          filters:
            branches:
              only: /test-.*/

      - deploy:
          context: org-global
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
