apiVersion: v1
kind: Service
metadata:
  labels:
    app: next-store
  name: next-store
spec:
  type: LoadBalancer
  ports:
    - port: 14401
      name: http-port
      targetPort: 14401
  selector:
    app: next-store
