apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-admin
  labels:
    app: next-admin
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    spec:
      containers:
        - name: next-admin
          resources:
            limits:
              cpu: "1"
              memory: 700Mi
            requests:
              cpu: 10m
              memory: 298Mi
