version: '3'
services:
  nginx:
    image: asia.gcr.io/instant-matter-785/meep-nginx:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=staging
      - API
      - DOMAIN
      - ADMIN_HOST
    links:
      - admin
      - next-admin
      - next-store
      - meepshop-app-market
  admin:
    image: asia.gcr.io/instant-matter-785/admin:latest
    environment:
      - API_HOST=${API_WITHOUT_PROTOCOL}
      - NODE_ENV=production
  next-admin:
    image: asia.gcr.io/instant-matter-785/next-admin:latest
    environment:
      - API_HOST=${API}
      - API_DOMAIN=${DOMAIN}
  next-store:
    image: asia.gcr.io/instant-matter-785/next-store:latest
    environment:
      - STORE_DOMAIN=${DOMAIN}
      - API_HOST=${API}
      - EXTERNAL_API_HOST=${API}
  meepshop-app-market:
    image: asia.gcr.io/instant-matter-785/meepshop-app-market:latest
    environment:
      - API_HOST=${API}
