export default ({ message }: Error) => {
  switch (message) {
    case 'FAIL_TIMEOUT':
    case 'FAIL_UNKNOWN_ECFIT_ERROR_CODE':
    case 'FAIL_01_FIELD_ORDER_NO_BLANK':
    case 'FAIL_02_FIELD_INVOICED_BLANK':
    case 'FAIL_03_FIELD_BAN_WRONG':
    case 'FAIL_04_FIELD_NPO_WRONG':
    case 'FAIL_05_BAN_NOT_ALLOWED_WHEN_NPO_FILLED':
    case 'FAIL_06_FIELD_DEMAND_CANNOT_BE_Y_WHEN_NPO_FILLED':
    case 'FAIL_07_INCOMPLETE_CUSTOMER_INFO':
    case 'FAIL_08_BLANK_ORDER_PRODUCT_OR_PRODUCT_QUANTITY_ZERO':
    case 'FAIL_09_FIELD_AMOUNT_WRONG':
    case 'FAIL_10_UNKNOWN_ERROR':
    case 'FAIL_11_ORDER_NOT_FOUND':
    case 'FAIL_12_FIELD_ARRIVE_LESS_THAN_NOW':
    case 'FAIL_13_DUPLICATE_ORDER_NO':
    case 'FAIL_14_WRONG_PRODUCT_BARCODE':
    case 'FAIL_15_FIELD_LOGISTICS_ID_WRONG':
    case 'FAIL_16_PRODUCT_NOT_FOUND':
    case 'FAIL_17_FIELD_ARRIVE_TYPE_WRONG':
    case 'FAIL_18_FILED_CREDIT_NO_WRONG':
    case 'FAIL_19_BUYER_REQUIRED_WHEN_FIELD_INVOICED_IS_Y':
    case 'FAIL_20_NO_BUYER_WHEN_FIELD_INVOICED_IS_N':
    case 'FAIL_21_FIELD_EMAIL_FORMAT_ERROR':
    case 'FAIL_22_FIELD_TAX_TYPE_WRONG':
    case 'FAIL_23_FIELD_CLEARANCE_MARK_WRONG':
    case 'FAIL_24_FIELD_PHONE_FORMAT_ERROR':
    case 'FAIL_41_FIELD_CODE_REQUIRED':
    case 'FAIL_42_STORE_PICK_UP_REQUIRE_CODE':
    case 'FAIL_43_CODE_NOT_ALLOWED_WHEN_NOT_STORE_PICK_UP':
    case 'FAIL_01_ORDER_NOT_FOUND':
    case 'FAIL_02_ORDER_STATUS_CANCELED_OR_CLOSED':
    case 'FAIL_03_ORDER_STATUS_WRONG_OR_NOT_ALLOWED':
      return false;

    default:
      return true;
  }
};
