apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: next-store-virtualservice
  namespace: default
spec:
  gateways:
  - unleash-gateway
  hosts:
  - '*.stage.meepcloud.com'
  http:
  - match:
    - uri:
        exact: /robots.txt
    - uri:
        exact: /pages/sitemap.xml
    - uri:
        exact: /sitemap.xml
    - uri:
        exact: /product/sitemap.xml
    name: sitemap
    route:
    - destination:
        host: meep-nginx
        port:
          number: 8080
  - match:
    - uri:
        prefix: /checkout/thank-you-page
    route:
    - destination:
        host: next-store
        port:
          number: 14401
  - match:
    - queryParams:
        resetCart:
          regex: "^(true|false)$"
    route:
    - destination:
        host: cart-generator
        port:
          number: 14401
  - route:
    - destination:
        host: storefront-reverse-proxy
        port:
          number: 8080
