export const LOCALE = [
  { value: 'zh_TW', text: '繁體中文' },
  { value: 'en_US', text: 'English' },
  { value: 'ja_JP', text: '日本語' },
  { value: 'vi_VN', text: 'Tiếng việt nam' },
  { value: 'fr_FR', text: 'Français' },
  { value: 'es_ES', text: 'Español' },
  { value: 'th_TH', text: 'ไทย' },
  { value: 'id_ID', text: 'Orang indonesia' },
];

export const TIMEZONE = [
  { value: '-11', text: 'MIT' },
  { value: '-10', text: 'HST' },
  { value: '-9', text: 'AKST' },
  { value: '-8', text: 'PST' },
  { value: '-7', text: 'MST' },
  { value: '-6', text: 'CST' },
  { value: '-5', text: 'EST' },
  { value: '-4', text: 'AST' },
  { value: '-3.5', text: 'NST' },
  { value: '-3', text: 'SAT' },
  { value: '-2', text: 'BRT' },
  { value: '-1', text: 'CVT' },
  { value: '+0', text: 'WET' },
  { value: '+1', text: 'CET' },
  { value: '+2', text: 'EET' },
  { value: '+3', text: 'MSK' },
  { value: '+3.5', text: 'IRT' },
  { value: '+4', text: 'META' },
  { value: '+4.5', text: 'AFT' },
  { value: '+5', text: 'METB' },
  { value: '+5.5', text: 'IDT' },
  { value: '+5.75', text: 'NPT' },
  { value: '+6', text: 'BHT' },
  { value: '+6.5', text: 'MRT' },
  { value: '+7', text: 'IST' },
  { value: '+8', text: 'EAT' },
  { value: '+9', text: 'FET' },
  { value: '+9.5', text: 'ACST' },
  { value: '+10', text: 'AEST' },
  { value: '+11', text: 'VTT' },
  { value: '+12', text: 'PSTB' },
  { value: '+13', text: 'PSTC' },
];

export const STORESTATUS = ['OPEN', 'CLOSE'];
