apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: next-store
  namespace: default
spec:
  scaleRef:
    kind: Deployment
    name: next-store
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
