apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-admin
  labels:
    app: next-admin
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: next-admin
  template:
    metadata:
      labels:
        app: next-admin
    spec:
      restartPolicy: Always
      containers:
      - name: next-admin
        image: asia.gcr.io/instant-matter-785/next-admin:tag
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 14405
          initialDelaySeconds: 15
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 14405
          initialDelaySeconds: 15
          periodSeconds: 3
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: next-admin
              key: external.env
        ports:
        - containerPort: 14405
          name: http-port
