apiVersion: v1
kind: Service
metadata:
  labels:
    app: next-admin
  name: next-admin
spec:
  type: LoadBalancer
  ports:
    - port: 14405
      name: http-port
      targetPort: 14405
  selector:
    app: next-admin
