/* eslint-disable camelcase */
import {
  MdHome,
  MdShoppingCart,
  MdShoppingBasket,
  MdLocalMall,
  MdPerson, // for mobileLayout menu
  MdSearch, // for searchBar
  MdPersonAdd,
  MdGroupAdd,
  MdSupervisorAccount,
  MdHelp,
  MdInfo,
  MdNewReleases,
  MdEqualizer,
  MdStar,
  MdStars,
  MdFavorite,
  MdLocalOffer,
  MdLoyalty,
  MdMonetizationOn,
  MdAttachMoney,
  MdCardGiftcard,
  MdEventNote,
  MdDateRange,
  MdEvent,
  MdThumbUp,
  MdCake,
  MdNotifications,
  MdPinDrop,
  MdPlace,
  MdCall,
  MdHeadsetMic,
  MdTextsms,
  MdForum,
  MdEmail,
  MdShare,
  MdAddShoppingCart,
  MdPersonOutline,
  MdHelpOutline,
  MdInfoOutline,
  MdFavoriteBorder,
  MdStarBorder,
  MdLocalAtm,
  MdMailOutline,
  MdChatBubbleOutline,
  MdTrendingUp,
  MdLocationSearching,
} from 'react-icons/md';

export default {
  home: MdHome,
  shopping_cart: MdShoppingCart,
  shopping_basket: MdShoppingBasket,
  local_mall: MdLocalMall,
  person: MdPerson,
  search: MdSearch,
  person_add: MdPersonAdd,
  group_add: MdGroupAdd,
  supervisor_account: MdSupervisorAccount,
  help: MdHelp,
  info: MdInfo,
  new_releases: MdNewReleases,
  equalizer: MdEqualizer,
  star: MdStar,
  stars: MdStars,
  favorite: MdFavorite,
  local_offer: MdLocalOffer,
  loyalty: MdLoyalty,
  monetization_on: MdMonetizationOn,
  attach_money: MdAttachMoney,
  card_giftcard: MdCardGiftcard,
  event_note: MdEventNote,
  date_range: MdDateRange,
  event: MdEvent,
  thumb_up: MdThumbUp,
  cake: MdCake,
  notifications: MdNotifications,
  pin_drop: MdPinDrop,
  place: MdPlace,
  call: MdCall,
  headset_mic: MdHeadsetMic,
  textsms: MdTextsms,
  forum: MdForum,
  email: MdEmail,
  share: MdShare,
  add_shopping_cart: MdAddShoppingCart,
  person_outline: MdPersonOutline,
  help_outline: MdHelpOutline,
  info_outline: MdInfoOutline,
  favorite_border: MdFavoriteBorder,
  star_border: MdStarBorder,
  local_atm: MdLocalAtm,
  mail_outline: MdMailOutline,
  chat_bubble_outline: MdChatBubbleOutline,
  trending_up: MdTrendingUp,
  location_searching: MdLocationSearching,
};
/* eslint-enable camelcase */
